# Generated by Django 3.1.3 on 2020-11-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langs', '0002_auto_20201119_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='language code'),
        ),
    ]
