# Generated by Django 3.1.3 on 2020-11-18 05:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('langs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(upload_to='persons', verbose_name='person avatar')),
                ('name', models.CharField(max_length=255, verbose_name='person name')),
                ('profession', models.CharField(max_length=255, verbose_name='person profession')),
                ('about', models.CharField(max_length=1000, verbose_name='information about person')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langs.language', verbose_name='language')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
    ]
