# Generated by Django 3.1.4 on 2021-01-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='persons', verbose_name='person avatar')),
                ('name', models.CharField(max_length=255, verbose_name='person name in English')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='person name in Russian')),
                ('profession', models.CharField(max_length=255, verbose_name='person profession in English')),
                ('profession_ru', models.CharField(blank=True, max_length=255, verbose_name='person profession in Russian')),
                ('about', models.CharField(max_length=1000, verbose_name='information about person in English')),
                ('about_ru', models.CharField(blank=True, max_length=1000, verbose_name='information about person in Russian')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'ordering': ('name',),
            },
        ),
    ]
