# Generated by Django 3.1.3 on 2020-11-18 05:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('langs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='game title')),
                ('slug', models.SlugField(verbose_name='game slug')),
                ('preview', models.ImageField(help_text='preferably 1000x225 px', upload_to='games', verbose_name='game preview')),
                ('short_description', models.CharField(max_length=1000, verbose_name='game short description')),
                ('description', tinymce.models.HTMLField(verbose_name='game description')),
                ('video', models.URLField(validators=[django.core.validators.URLValidator(message='A video link need to be from YouTube', regex='https://(?:www.)?youtube.com/watch.*v=.*')], verbose_name='game video link on youtube')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='langs.language', verbose_name='language')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
                'ordering': ('pub_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='games', verbose_name='game image')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='games.game', verbose_name='game')),
            ],
            options={
                'verbose_name': 'game image',
                'verbose_name_plural': 'game images',
            },
        ),
    ]
