# Generated by Django 3.1.3 on 2020-11-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langs', '0002_auto_20201119_0032'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('slug', 'language')},
        ),
    ]
