# Generated by Django 3.1.3 on 2020-11-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201119_0032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('slug', 'language'), name='unique_games'),
        ),
    ]
