# Generated by Django 3.1.2 on 2020-10-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201015_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='preview',
            field=models.ImageField(help_text='preferably 1000pxx225px', upload_to='games', verbose_name='game preview'),
        ),
    ]
