# Generated by Django 3.1.2 on 2020-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20201015_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='preview',
            field=models.ImageField(help_text='preferably 1000x225 px', upload_to='games', verbose_name='game preview'),
        ),
    ]
